"""
Django settings for arka project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from typing import Optional, List

from .utils import (
    build_broker_url,
    build_rabbitmq_api_url,
    check_logdir,
    load_secret_key,
    load_config_file,
)
from .logging import load_logging_defaults


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Environment mode
# Default: production
DJANGO_ENV: str = os.environ.get("DJANGO_ENV", "production").lower()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Load secret key early
if DJANGO_ENV == "production":
    SECRET_KEY = load_secret_key(DJANGO_ENV, BASE_DIR)
else:
    SECRET_KEY = "!dev-secret-key!"

# SECURITY WARNING: don't run with debug turned on in production!
# Default: From DJANGO_ENV
DEBUG: bool = True if DJANGO_ENV == "development" else False
# Do not allow Debug to be set in production environment
if DEBUG and DJANGO_ENV == "production":
    raise ValueError("Do not use DEBUG in production!!")

ALLOWED_HOSTS: List[str] = []

CSRF_TRUSTED_ORIGINS: List[str] = []

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/login/"
LOGIN_URL = "/login/"

# Application definition

INSTALLED_APPS: List[str] = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_celery_results",
    "django_celery_beat",
    "arka",
    "forj",
]

# Modular apps inclusion
raw_apps = os.environ.get("ENABLED_APPS", "")
ENABLED_APPS_SET = {app.strip().upper() for app in raw_apps.split(",")} if raw_apps else set()

ALLOWED_APPS = {"AERA", "PYMAP", "DBTOOL", "NETTOOLS", "MXR"}
invalid_apps = ENABLED_APPS_SET - ALLOWED_APPS
if invalid_apps:
    raise ValueError(f"Unknown modular apps in ENABLED_APPS: {invalid_apps}")

if "AERA" in ENABLED_APPS_SET:
    INSTALLED_APPS.append("aera")
if "PYMAP" in ENABLED_APPS_SET:
    INSTALLED_APPS.append("pymap")
if "DBTOOL" in ENABLED_APPS_SET:
    INSTALLED_APPS.append("dbtool")
if "NETTOOLS" in ENABLED_APPS_SET:
    INSTALLED_APPS.append("nettools")
if "MXR" in ENABLED_APPS_SET:
    INSTALLED_APPS.append("mxr")

MIDDLEWARE: List[str] = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "arka.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "arka.context_processors.project_version",
                "arka.context_processors.active_app_version",
                "arka.context_processors.modular_apps",
            ],
        },
    },
]

WSGI_APPLICATION = "arka.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Cache
# https://docs.djangoproject.com/en/5.2/topics/cache/
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379",
    },
    "dbcache": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "my_cache_table",
    },
}

# Logging
# https://docs.djangoproject.com/en/5.2/topics/logging/
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = os.getenv("STATIC_ROOT", None)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Celery configs
# https://docs.celeryq.dev/en/stable/django/index.html

CELERY_BROKER_URL = None
RABBITMQ_API_URL = None
CELERY_TIMEZONE = "Europe/Lisbon"
CELERY_RESULT_BACKEND: str = "django-db"
CELERY_RESULT_SERIALIZER = "json"
CELERY_RESULT_EXTENDED = True
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_TASK_SOFT_TIME_LIMIT = 14400  # 4 hours
CELERY_TASK_TIME_LIMIT = 14700  # 4 hours 5 minutes
CELERY_WORKER_MAX_TASKS_PER_CHILD = 5

# RabbitMQ 4.3+ Compatibility (Avoid transient non-exclusive queues)
CELERY_WORKER_ENABLE_REMOTE_CONTROL = False
CELERY_WORKER_SEND_TASK_EVENTS = False
CELERY_TASK_SEND_SENT_EVENT = False
CELERY_WORKER_GOSSIP = False
CELERY_WORKER_MINGLE = False
# CELERY_TASK_TRACK_STARTED: bool = True
# CELERY_TASK_ALWAYS_EAGER: bool = True # Set True for local testing without a worker

# Application log directory
ARKA_LOGDIR: Optional[str] = None


# Custom config
CUSTOM_CONFIG = load_config_file(DJANGO_ENV, BASE_DIR)

# Config overrides
# 1. Apply Config
DATABASES.update(CUSTOM_CONFIG.get("DATABASES", DATABASES))
CACHES.update(CUSTOM_CONFIG.get("CACHES", CACHES))
ALLOWED_HOSTS = CUSTOM_CONFIG.get("ALLOWED_HOSTS", ALLOWED_HOSTS)
CSRF_TRUSTED_ORIGINS = CUSTOM_CONFIG.get("CSRF_TRUSTED_ORIGINS", CSRF_TRUSTED_ORIGINS)
CELERY_BROKER_URL = CUSTOM_CONFIG.get("CELERY_BROKER_URL", CELERY_BROKER_URL)
CELERY_RESULT_BACKEND = CUSTOM_CONFIG.get(
    "CELERY_RESULT_BACKEND", CELERY_RESULT_BACKEND
)

# 2. Env Overrides (Priority)
ARKA_LOGDIR = os.environ.get("ARKA_LOGDIR")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", CELERY_RESULT_BACKEND)

# 3. Finalize
if ARKA_LOGDIR is None:
    ARKA_LOGDIR = str(Path(BASE_DIR, "ARKA_LOGS").resolve())

# Load logging: either from config or defaults
custom_logging = CUSTOM_CONFIG.get("LOGGING")
if isinstance(custom_logging, dict):
    LOGGING.update(custom_logging)

# Ensure file handlers use the correct ARKA_LOGDIR
handlers = LOGGING.get("handlers", {})
if isinstance(handlers, dict):
    for h in handlers.values():
        if isinstance(h, dict) and h.get("filename"):
            f = str(h["filename"])
            if not os.path.isabs(f):
                h["filename"] = os.path.join(str(ARKA_LOGDIR), f)
            else:
                # If it's absolute, keep it but ensure it's a string
                h["filename"] = f
else:
    LOGGING.update(load_logging_defaults(str(ARKA_LOGDIR)))
try:
    # Use the same config for both Broker and Management API
    RABBITMQ_API_URL = build_rabbitmq_api_url(CELERY_BROKER_URL)
    CELERY_BROKER_URL = build_broker_url(CELERY_BROKER_URL)
    if DJANGO_ENV == "production":
        check_logdir(ARKA_LOGDIR)
        if STATIC_ROOT is None:
            raise ValueError(f"Static root is not defined: {STATIC_ROOT}")
except Exception as e:
    if DJANGO_ENV == "migrations":
        print(
            "FAILED TO LOAD CELERY_BROKER_URL THIS IS ONLY AN OVERRIDE TO RUN LOCALLY MAKEMIGRATIONS DJANGO MANAGEMENT COMMAND!!"
        )
        print(f"INSTALLED_APPS: {INSTALLED_APPS}")
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.sqlite3",
                "NAME": BASE_DIR / "db.sqlite3",
            }
        }
        pass
    else:
        raise e

if DJANGO_ENV == "migrations":
    print(
        "DEFAULTING DATABASE TO SQLITE!! THIS IS ONLY AN OVERRIDE TO RUN LOCALLY MAKEMIGRATIONS DJANGO MANAGEMENT COMMAND!!"
    )
    print(f"INSTALLED_APPS: {INSTALLED_APPS}")
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
