"""
Django settings for arka project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import json
from pathlib import Path
from typing import Optional, List


from .utils import build_broker_url, check_logdir, load_secret_key
from .logging import load_logging_defaults

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Environment mode
# Default: production
DJANGO_ENV: str = os.environ.get("DJANGO_ENV", "production").lower()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Default: None, set in development, loaded in production
SECRET_KEY: Optional[str] = None

# SECURITY WARNING: don't run with debug turned on in production!
# Default: From DJANGO_ENV
DEBUG: bool = True if DJANGO_ENV == "development" else False
# Do not allow Debug to be set in production environment
if DEBUG and DJANGO_ENV == "production":
    raise ValueError("Do not use DEBUG in production!!")

# Application log directory
ARKA_LOGDIR: Optional[str] = os.environ.get("ARKA_LOGDIR", None)
if ARKA_LOGDIR is None:
    ARKA_LOGDIR = str(Path(BASE_DIR, "ARKA_LOGS").resolve())

ALLOWED_HOSTS: List[str] = []


# Application definition

INSTALLED_APPS: List[str] = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_celery_results",
    "forj",
    "pymap",
    "aera",
]

MIDDLEWARE: List[str] = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "arka.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "arka.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Cache
# https://docs.djangoproject.com/en/5.2/topics/cache/
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379",
    },
    "dbcache": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "my_cache_table",
    },
}

# Logging
# https://docs.djangoproject.com/en/5.2/topics/logging/
LOGGING = load_logging_defaults(ARKA_LOGDIR)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.getenv("STATIC_ROOT", None)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Celery configs
# https://docs.celeryq.dev/en/stable/django/index.html

CELERY_BROKER_URL: Optional[str] = None
CELERY_TIMEZONE = "Europe/Lisbon"
CELERY_RESULT_BACKEND: str = "django-db"
CELERY_RESULT_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
# CELERY_TASK_TRACK_STARTED: bool = True
# CELERY_TASK_ALWAYS_EAGER: bool = True # Set True for local testing without a worker

# Custom config
CUSTOM_CONFIG = {}
CONFIG_FILE = BASE_DIR / "config.json" if DJANGO_ENV == "production" else BASE_DIR / "config.dev.json"
if CONFIG_FILE.exists():
    with open(CONFIG_FILE) as f:
        CUSTOM_CONFIG = json.load(f)


# Config overrides
ALLOWED_HOSTS = CUSTOM_CONFIG.get("ALLOWED_HOSTS", ALLOWED_HOSTS)
# CSRF_TRUSTED_ORIGINS = CUSTOM_CONFIG.get("CSRF_TRUSTED_ORIGINS", CSRF_TRUSTED_ORIGINS)
CACHES = CUSTOM_CONFIG.get("CACHES", CACHES)
LOGGING = CUSTOM_CONFIG.get("LOGGING", LOGGING)
DATABASES = CUSTOM_CONFIG.get("DATABASES", DATABASES)

if not DEBUG:
    try:
        SECRET_KEY = load_secret_key(DJANGO_ENV, BASE_DIR, SECRET_KEY)
        check_logdir(ARKA_LOGDIR)
    except Exception as e:
        raise e
