services:
  # ---------- Cache ----------
  redis:
    image: "docker.io/library/redis:latest"
    ports:
      - "6379:6379"
    restart: unless-stopped
  # ---------- Broker ----------
  rabbitmq:
    build:
      context: .
      dockerfile: docker/rabbitmq/Dockerfile
    image: rabbitmq:arka-prod
    container_name: rabbitmq-arka
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST:-forj}
      RABBITMQ_DISK_FREE_LIMIT: 2GB
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
  # ---------- DB ----------
  postgres:
    image: "docker.io/library/postgres:latest"
    ports:
      - "5432:5432"
    restart: unless-stopped
    hostname: postgres-arka
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: ${POSTGRES_DB:-arka}
      POSTGRES_USER: ${POSTGRES_USER:-arka}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST:-127.0.0.1}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-arka} -d ${POSTGRES_DB:-arka}" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
  # ---------- DB Pooling -----------
  pgbouncer:
    image: pgbouncer/pgbouncer:latest
    container_name: pgbouncer-arka
    environment:
      - DATABASES_HOST=${POSTGRES_HOST:-postgres}
      - DATABASES_PORT=${POSTGRES_PORT:-5432}
      - DATABASES_USER=${POSTGRES_USER}
      - DATABASES_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASES_DBNAME=${POSTGRES_DB}
      - PGBOUNCER_POOL_MODE=transaction # CRITICAL for Django
      - PGBOUNCER_MAX_CLIENT_CONN=100
      - PGBOUNCER_DEFAULT_POOL_SIZE=25
    ports:
      - "6432:6432"
    restart: unless-stopped
    depends_on:
      - postgres
  # ---------- Arka-django ----------
  arka:
    build:
      context: .
      dockerfile: Dockerfile
      target: final-production
      args:
        ENABLE_AERA: ${ENABLE_AERA:-false}
        ENABLE_PYMAP: ${ENABLE_PYMAP:-false}
        MODULE_SOURCE: ${MODULE_SOURCE:-git}
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-arka}
      - POSTGRES_USER=${POSTGRES_USER:-arka}
      - POSTGRES_HOST=pgbouncer-arka
      - POSTGRES_PORT=6432
      - DJANGO_ENV=${DJANGO_ENV:-production}
      - STATIC_ROOT=${STATIC_ROOT}
      - ARKA_LOGDIR=${ARKA_LOGDIR:-/app/ARKA_LOGS}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE:-arka.settings}
      - CONTAINER_USER=arka
      - PYTHONPATH=/app/src
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    volumes:
      - shared_logs:${ARKA_LOGDIR:-/app/ARKA_LOGS}
      - static_root:$STATIC_ROOT
      - type: bind
        source: ./secrets
        target: /run/secrets
        read_only: true
    command: /app/scripts/django_init.sh
  # ---------- Nginx ----------
  arka.internal:
    build:
      context: .
      dockerfile: docker/Dockerfile.nginx
      args:
        GID: 1002
        GROUPNAME: ${CONTAINER_GROUP:-arka}
    ports:
      - "5001:80"
      - "5000:443"
    environment:
      STATIC_ROOT: ${STATIC_ROOT}
    volumes:
      - ./docker/templates:/etc/nginx/templates
      - static_root:/var/www/static:ro
    depends_on:
      - arka
  # ---------- Forj-celery ----------
  forj: &forj_base
    init: true
    stop_grace_period: 5m
    build:
      context: .
      dockerfile: Dockerfile
      target: final-production-worker
      args:
        ENABLE_AERA: ${ENABLE_AERA:-false}
        ENABLE_PYMAP: ${ENABLE_PYMAP:-false}
        MODULE_SOURCE: ${MODULE_SOURCE:-git}
    environment:
      - DJANGO_ENV=${DJANGO_ENV:-production}
      - ARKA_LOGDIR=${ARKA_LOGDIR:-/app/ARKA_LOGS}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE:-arka.settings}
      - CONTAINER_USER=forj
      - PYTHONPATH=/app/src
    depends_on:
      - rabbitmq
    volumes:
      - shared_logs:${ARKA_LOGDIR:-/app/ARKA_LOGS}
      - type: bind
        source: ./secrets
        target: /run/secrets
        read_only: true
    deploy:
      mode: replicated
      replicas: ${WORKER_REPLICAS:-1}
    command: /app/scripts/celery_init.sh worker
  # ---------- Forj-beat ----------
  forj-scheduler:
    <<: *forj_base
    deploy:
      mode: global
    depends_on:
      - forj
    volumes:
      - shared_logs:${ARKA_LOGDIR:-/app/ARKA_LOGS}
      - type: bind
        source: ./secrets
        target: /run/secrets
        read_only: true
    command: /app/scripts/celery_init.sh beat

  pgadmin:
    image: dpage/pgadmin4:latest
    profiles:
      - monitor
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@arka.internal}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-PGAdmin}
    ports:
      - 9001:80
  rinsight:
    image: redislabs/redisinsight:latest
    profiles:
      - monitor
    restart: always
    ports:
      - 5540:5540

volumes:
  pgdata:
  static_root:
  rabbitmq_data:
  shared_logs:
