services:
  rabbitmq:
    volumes:
      - rabbitmq_data_dev:/var/lib/rabbitmq

  arka:
    volumes:
      - shared_logs_dev:$ARKA_LOGDIR
      - ./src/arka:/home/arka/app/arka/
      - ./src/forj:/home/arka/app/forj/
      - ./src/modular_apps:/home/arka/app/modular_apps/
    # command: /home/arka/app/.venv/bin/python manage.py runserver 0.0.0.0:8000
    command: tail -f /dev/null

  forj:
    volumes:
      - shared_logs_dev:$ARKA_LOGDIR
      - ./src/arka:/home/arka/app/arka/
      - ./src/forj:/home/arka/app/forj/
      - ./src/modular_apps:/home/forj/app/modular_apps/
    #command: /home/forj/app/.venv/bin/celery -A forj.celery worker -l debug
    command: tail -f /dev/null

  forj-scheduler:
    command: tail -f /dev/null

volumes:
  static_root_dev:
  rabbitmq_data_dev:
  shared_logs_dev: