services:
  rabbitmq:
    volumes:
      - rabbitmq_data_dev:/var/lib/rabbitmq
  postgres:
    volumes:
      - pgdata_dev:/var/lib/postgresql
  arka:
    environment:
      - ARKA_DEV_MODE=true
      - ARKA_EDITABLE_MODULES=pymap,aera
      - ARKA_ENABLED_MODULES=pymap,aera
      - PYMAP_LOCAL_PATH=${PYMAP_LOCAL_PATH:-./src/modular_apps/Pymap}
      - AERA_LOCAL_PATH=${AERA_LOCAL_PATH:-./src/modular_apps/AERA}
    volumes:
      - shared_logs_dev:$ARKA_LOGDIR
      - static_root_dev:$STATIC_ROOT
      - ./src/arka:/home/arka/app/arka/
      - ./src/templates:/home/arka/app/templates
      - ./src/static:/home/arka/app/static
      - ./src/forj:/home/arka/app/forj/
      - ${PYMAP_LOCAL_PATH:-./src/modular_apps/Pymap}:/modules/pymap
      - ${AERA_LOCAL_PATH:-./src/modular_apps/AERA}:/modules/aera
    ports:
      - "8000:8000"
    command: /home/arka/app/init.sh
    # command: tail -f /dev/null

  forj:
    environment:
      - ARKA_DEV_MODE=true
      - ARKA_EDITABLE_MODULES=pymap,aera
      - ARKA_ENABLED_MODULES=pymap,aera
      - PYMAP_LOCAL_PATH=${PYMAP_LOCAL_PATH:-./src/modular_apps/Pymap}
      - AERA_LOCAL_PATH=${AERA_LOCAL_PATH:-./src/modular_apps/AERA}
    volumes:
      - shared_logs_dev:$ARKA_LOGDIR
      - static_root_dev:$STATIC_ROOT
      - ./src/arka:/home/forj/app/arka/
      - ./src/templates:/home/forj/app/templates
      - ./src/static:/home/forj/app/static
      - ./src/forj:/home/forj/app/forj/
      - ./src/db.sqlite3:/home/forj/app/db.sqlite3
      - ${PYMAP_LOCAL_PATH:-./src/modular_apps/Pymap}:/modules/pymap
      - ${AERA_LOCAL_PATH:-./src/modular_apps/AERA}:/modules/aera
    command: /home/forj/app/init.sh worker

  forj-scheduler:
    environment:
      - ARKA_DEV_MODE=true
      - ARKA_ENABLED_MODULES=pymap,aera
      - ARKA_EDITABLE_MODULES=pymap,aera
    volumes:
      - shared_logs_dev:$ARKA_LOGDIR
      - static_root_dev:$STATIC_ROOT
      - ./src/arka:/home/forj/app/arka/
      - ./src/templates:/home/forj/app/templates
      - ./src/static:/home/forj/app/static
      - ./src/forj:/home/forj/app/forj/
      - ${PYMAP_LOCAL_PATH:-./src/modular_apps/Pymap}:/modules/pymap
      - ${AERA_LOCAL_PATH:-./src/modular_apps/AERA}:/modules/aera
    command: /home/forj/app/init.sh beat

volumes:
  pgdata_dev:
  static_root_dev:
  rabbitmq_data_dev:
  shared_logs_dev:
